### ISSUE TITLE
feat: investigate possibly missing features

### ISSUE THREAD

**Issue by xynydev** [blue-build/github-action#2]
Are these things, that are in the the startingpoint action, missing from here, or are they implemented in [blue-build/cli](https://github.com/blue-build/cli) (@gmpinder) ?
- Check SIGNING_SECRET matches cosign.pub
- Verify base image
- Generate tags
- Lowercase Registry & Image

**Comment by gmpinder** [comment]
* Check SIGNING_SECRET matches cosign.pub - https://github.com/blue-build/cli/blob/dbbd087b5ba3dc7a6bf8f3fa9be2cdb569d6cecb/src/commands/build.rs#L762
* Verify base image - NOPE! Needs to be done
* Generate tags - https://github.com/blue-build/cli/blob/dbbd087b5ba3dc7a6bf8f3fa9be2cdb569d6cecb/src/commands/template.rs#L64
* Lowercase Registry & Image - I don't think so, good idea to fix and easy to implement

**Comment by gmpinder** [comment]
Lowercase registry is being fixed here: https://github.com/blue-build/cli/pull/8

**Comment by xynydev** [comment]
Should the image verification be implemented here with EyeCantCU's action (easy), or in cli?

**Comment by gmpinder** [comment]
> Should the image verification be implemented here with EyeCantCU's action (easy), or in cli?

If it just involves inspecting it for a label, we can totally do that in the tool. Plus I'll need that to make sure we're using the right version number on the image instead of latest

**Comment by qoijjj** [comment]
FYI, not only is base image verification needed but also custom base image verification, if using EyeCantCU's action:

```
  - name: Verify base image
        if: ${{ ! contains(env.IMAGE_NAME, 'wayblue') }}
        uses: EyeCantCU/cosign-action/verify@v0.2.2
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}

      - name: Verify base image
        if: ${{ contains(env.IMAGE_NAME, 'wayblue') }}
        uses: EyeCantCU/cosign-action/verify@v0.2.2
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}
          registry: 'ghcr.io/wayblueorg'
          pubkey: 'https://raw.githubusercontent.com/wayblueorg/wayblue/live/cosign.pub'
```

Regardless, the registry and pubkey need to be available as parameters.
