### ISSUE TITLE
feat: add missing inputs (from bb env vars)

### ISSUE THREAD

**Issue by xynydev** [blue-build/github-action#4]
@gmpinder help needed

First of all, is `PR_EVENT_NUMBER` used for anything? I couldn't find a reference to it in https://github.com/blue-build/cli.

Others probably needed:
- registry path
- cosign password

**Comment by gmpinder** [comment]
```
PR_EVENT_NUMBER: ${{ inputs.registry_token }}
```

Did I actually do this? That was dumb of me. It's supposed to grab the pull request number, please remove this line for now as that is a security issue

**Comment by gmpinder** [comment]
The README of the cli tool has this:

```yaml
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          PR_EVENT_NUMBER: ${{ github.event.number }}
          REGISTRY_TOKEN: ${{ github.token }}
```
