### ISSUE TITLE
investigate and discuss composite actions vs reusable workflows

### ISSUE THREAD

**Issue by xynydev** [blue-build/github-action#67]
Currently the BlueBuild GitHub Action is a [composite action](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action). 

It could also technically be a [reusable workflow](https://docs.github.com/en/actions/sharing-automations/reusing-workflows#next-steps).    
This would allow us to specify custom build matrices inside the reusable component, centralizing the way the workflow is configured, and possibly allowing us to integrate a more complex build system for creating recipes (ex. jsonnet) within the GitHub matrixing. 

The composite action could still live alongside the reusable workflow, and be used by it. We could switch to using the reusable workflow by default in the template, since it would have more streamlined configuration and more features. Falling back to using the composite action would be possible for power users to do 'unsupported things' (such as #53), too, of course. 

Read more about the differences here:
https://docs.github.com/en/actions/sharing-automations/avoiding-duplication

**Comment by gmpinder** [comment]
Do you have an example of what that would look like to the end user?

**Comment by xynydev** [comment]
This is adapted from [m2's setup](https://github.com/m2Giles/m2os/blob/main/.github/workflows/build.yml) without testing

```yaml
name: Build images
on:
  schedule:
    - cron: "00 06 * * *" # build at 06:00 UTC every day 
                          # (20 minutes after last ublue images start building)
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-images:
    name: Build images
    uses: blue-build/workflow/file.yml@v1.7
    secrets: inherit
    with:
      recipe:
          # !! Add your recipes here 
          - recipe.yml

       # enabled by default, set to false if your image is small and you want faster builds      
       maximize_build_space: true
```
