### ISSUE TITLE
Action doesn't work at all if you have a dash at the end of username

### ISSUE THREAD

**Issue by Ferenc-** [blue-build/github-action#81]
The failure is logged as:
```
[15:27:58 ERROR] => Failed:
2563
  × Unable to parse image ghcr.io/endswithdash-/anything
2564
  ╰─▶ invalid reference format
2565
```

The default `registry_namespace` causes invalid reference format if the GH repo owner has a dash at the end:
```
  registry_namespace:
    description: |
      The namespace on the registry to push to.

      Example: `ublue-os`
    required: false
    default: ${{ github.repository_owner }}
```
See: https://github.com/orgs/community/discussions/27186
